name: Test Github Packages for Multi-Arch containers

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:

jobs:

  per-arch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - arm64
          - arm32
          - amd64
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup QEMU user-mode emulation
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu qemu-user-static binfmt-support --no-install-recommends
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Log docker into Github Container Registry
      run: echo ${{ secrets.CI_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Create per-arch labels
      run: make test-build-${{ matrix.arch }}

    - name: Push per-arch labels
      run: make test-docker-per-arch-${{ matrix.arch }}

  multi-arch:
    runs-on: ubuntu-latest
    needs: per-arch

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup QEMU user-mode emulation
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu qemu-user-static binfmt-support --no-install-recommends
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Log docker into Github Container Registry
      run: echo ${{ secrets.CI_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Create and push multi-arch label
      run: |
        make test-docker-push-multi-arch-create
        make test-docker-push-multi-arch-inspect
        make test-docker-push-multi-arch-push

  per-arch-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - arm64
          - arm32
          - amd64
    needs: multi-arch

    steps:
    - name: Log docker into Github Container Registry
      run: echo ${{ secrets.CI_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Pull multi-arch label
      run: make test-docker-push-multi-arch-pull

